# Generated by Django 3.2.7 on 2021-11-01 22:45

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('phone', models.CharField(max_length=50)),
                ('security_question', models.CharField(choices=[('What Is your favorite book?', 'What Is your favorite book?'), ('What is your mother’s maiden name?', 'What is your mother’s maiden name?'), ('What is your favorite food?', 'What is your favorite food?'), ('What city were you born in?', 'What city were you born in?'), ('Where is your favorite place to vacation?', 'Where is your favorite place to vacation?'), ('What was the first company that you worked for?', 'What was the first company that you worked for?')], default='Active', max_length=100)),
                ('security_answer', models.CharField(max_length=100)),
                ('account_number', models.CharField(default=accounts.models.random_account, max_length=200, unique=True)),
                ('available_bal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Dormant', 'Dormant'), ('Deactivated', 'Deactivated')], default='Active', max_length=11)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('query', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='UpdateUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('passport', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('next_of_kin', models.CharField(max_length=100)),
                ('relationship_nok', models.CharField(max_length=50)),
                ('phone_nok', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profile Update',
            },
        ),
        migrations.CreateModel(
            name='LocalTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_fullname', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=100)),
                ('to_account', models.CharField(max_length=30)),
                ('to_account_type', models.CharField(choices=[('Checking', 'Checking'), ('Savings', 'Savings')], default='Savings', max_length=20)),
                ('transfer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transfer_description', models.CharField(blank=True, max_length=100, null=True)),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Successful', 'Successful'), ('Declined', 'Declined')], default='Pending', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Local Tranfers',
            },
        ),
        migrations.CreateModel(
            name='InternationalTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_fullname', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_country', models.CharField(max_length=100)),
                ('to_account', models.CharField(max_length=30)),
                ('to_account_type', models.CharField(choices=[('Checking', 'Checking'), ('Savings', 'Savings')], default='Savings', max_length=20)),
                ('routing_number', models.CharField(max_length=50)),
                ('iban_number', models.CharField(max_length=50)),
                ('transfer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency_type', models.CharField(default='USD', max_length=20)),
                ('transfer_description', models.CharField(blank=True, max_length=100, null=True)),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Successful', 'Successful'), ('Declined', 'Declined')], default='Pending', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'International Tranfers',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_fullname', models.CharField(max_length=200)),
                ('to_account', models.CharField(max_length=30)),
                ('transaction_type', models.CharField(blank=True, choices=[('Credit', 'Credit'), ('Debit', 'Debit')], default='Credit', max_length=11, null=True)),
                ('transaction_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('transaction_description', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_date', models.DateField()),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Successful', 'Successful'), ('Declined', 'Declined')], default='Successful', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Transaction History',
            },
        ),
    ]
