# Generated by Django 3.2.7 on 2021-11-04 17:50

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationaltransfer',
            name='get_otp',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='internationaltransfer',
            name='otp',
            field=models.CharField(default=accounts.models.make_otp, editable=False, max_length=5, unique=True),
        ),
        migrations.AddField(
            model_name='localtransfer',
            name='get_otp',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='localtransfer',
            name='otp',
            field=models.CharField(default=accounts.models.make_otp, editable=False, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('G', 'Gender'), ('M', 'Male'), ('F', 'Female')], default='G', max_length=1),
        ),
    ]
